[project]
name = "project-storage"
version = "0.1.0"
description = ""
authors = [
    {name = "glebzlat",email = "gleb.zlatanov@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard] (>=0.141.1,<0.142.0)",
    "pydantic-settings (>=2.14.2,<3.0.0)",
    "httpx2 (>=2.9.1,<3.0.0)",
    "sqlalchemy (>=2.0.51,<3.0.0)",
    "alembic (>=1.18.5,<2.0.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "pwdlib[argon2] (>=0.3.0,<0.4.0)",
    "pyjwt (>=2.13.0,<3.0.0)",
    "pytest-mock (>=3.15.1,<4.0.0)",
    "sqlalchemy-utils (>=0.42.1,<0.43.0)"
]

[tool.poetry]
packages = [{include = "project_storage", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "mypy (>=2.3.0,<3.0.0)",
    "poethepoet (>=0.48.0,<0.49.0)"
]

[tool.poe.tasks]
test = "pytest --cov=src/project_storage"
pep8 = "flake8 src/project_storage"
mypy = "mypy src/project_storage"

[tool.mypy]
plugins = ["pydantic.mypy"]

[tool.pytest]
pythonpath = ["src"]
