"""Add uuid and hashed_password

Revision ID: 5986676e7ac8
Revises: cba5ac9bda10
Create Date: 2026-08-07 12:22:54.644279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5986676e7ac8'
down_revision: Union[str, Sequence[str], None] = 'cba5ac9bda10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uuid', sa.UUID(), nullable=False))
    op.add_column('user', sa.Column('hashed_password', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'uuid')
    # ### end Alembic commands ###
