"""add FK ON DELETE CASCADE

Revision ID: e1932b7438bd
Revises: a49b65bdce8c
Create Date: 2026-08-16 12:37:51.312535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1932b7438bd'
down_revision: Union[str, Sequence[str], None] = 'a49b65bdce8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_participants_project_id_fkey'), 'project_participants', type_='foreignkey')
    op.drop_constraint(op.f('project_participants_user_id_fkey'), 'project_participants', type_='foreignkey')
    op.create_foreign_key(None, 'project_participants', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_participants', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_participants', type_='foreignkey')
    op.drop_constraint(None, 'project_participants', type_='foreignkey')
    op.create_foreign_key(op.f('project_participants_user_id_fkey'), 'project_participants', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('project_participants_project_id_fkey'), 'project_participants', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###
